[package]
name = "outlaw-format"
version = "2.0.0"
authors = ["Terr <git@terr.nl>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[profile.release]
lto = true
