[package]
name = "outlaw-format"
version = "0.1.0"
authors = ["Terr <git@terr.nl>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
